test:
  image: ibmcom/swift-ubuntu:4.0.3
  volumes:
    - ./:/Kitura
  command: bash -c "cd /Kitura && swift package  --build-path .build-ubuntu clean && swift build  --build-path .build-ubuntu && swift test  --build-path .build-ubuntu"
