version: 2

jobs:
  macos:
    macos:
      xcode: "9.2"
    steps:
      - checkout
      - run: swift build
      - run: swift test

  linux:
    docker:
      - image: codevapor/swift:4.1
    steps:
      - checkout
      - run: 
          name: Compile code
          command: swift build
      - run: 
          name: Run unit tests
          command: swift test

  linux-release:
    docker:
      - image: codevapor/swift:4.1
    steps:
      - checkout
      - run: 
          name: Compile code with optimizations
          command: swift build -c release


  linux-api-template:
    docker:
      - image: codevapor/swift:4.1
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: ""
    steps:
      - run:
          name: Clone API Template
          command: git clone -b beta https://github.com/vapor/api-template.git
          working_directory: ~/
      - run:
          name: Unpin dependencies
          command: rm Package.resolved
          working_directory: ~/api-template
      - run:
          name: Switch API Template to this Vapor revision
          command: swift package edit Vapor --revision $CIRCLE_SHA1
          working_directory: ~/api-template
      - run:
          name: Run API Template unit tests
          command: swift test
          working_directory: ~/api-template



workflows:
  version: 2
  tests:
    jobs:
      - linux
      - linux-release
      - linux-api-template
      # - macos

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
                
    jobs:
      - linux
      # - macos

